version: '3.8'

volumes:
  payara:

services:
  payara:
    container_name: payara
    build:
      context: .
    restart: always
    environment:
        DOMAIN_NAME: domain1
    volumes:
      - payara:/opt/payara/appserver/glassfish
    ports:
      - 8080:8080
      - 4848:4848
    networks:
        - tdp-net

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - tdp-net


  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - tdp-net
    ports:
      - 8081:8080

networks:
  tdp-net:
    name: tdp-net
    driver: bridge
