version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db_tpd
    environment:
      POSTGRES_DB: tpdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - tpdnet
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8099:8080"
    networks:
      - tpdnet

networks:
  tpdnet:
    driver: bridge

volumes:
  pg_data:
